### ISSUE TITLE
cwd param dont work as expected

### ISSUE THREAD

**Issue by mightydok** [puppetlabs/puppetlabs-powershell#123] opened 2016-07-05 12:54 UTC
After upgrade to 2.0.1 version of plugin i notice that cwd param broken, and dont change path to value.
Example script:

```
  exec { "cwd test":
    cwd      => 'c:/windows/',
    command  => 'get-location',
    provider =>  powershell,
  }
```
At 1.0.6 version all works fine.

**Comment by glennsarti** [comment] 2016-07-05 17:07
@mightydok Thanks for the issue report.  I've reproduced the issue as well.  Would you be able to raise a ticket as per https://github.com/puppetlabs/puppetlabs-powershell/blob/master/CONTRIBUTING.md

**Comment by glennsarti** [comment] 2016-07-05 17:19
@mightydok To speed up resolution of this issue, I've raised https://tickets.puppetlabs.com/browse/MODULES-3565 on your behalf.

**Comment by mightydok** [comment] 2016-07-05 17:43
@glennsarti thnx for issue at puppetlabs.com. 
About CONTRIBUTING.md - i dont know what i need to do, this file describe how make PR. What should i do?

**Comment by glennsarti** [comment] 2016-07-05 17:45
@mightydok There is a section in the CONTRIBUTING section about how to raise an ticket.  However as I've done that for you already, there's nothing required of you.

**Comment by mightydok** [comment] 2016-07-05 17:50
@glennsarti oh, ok. Thnx again.

**Comment by ferventcoder** [comment] 2016-07-06 20:06
Since we have an issue linked up with this, I'm going to close this ticket.

**Closed by ferventcoder** 2016-07-06 20:06 UTC
